### ISSUE TITLE
Exception Thrown When Filtering by Entity Id

### ISSUE THREAD

**Issue by DiggaTheWolf** [rappen/FetchXMLBuilder#373] opened 2020-09-02 08:39 UTC
Hi Jonas

I'm getting an exception thrown when applying a filter condition which targets any entity id (PK) using the UI, manual edits are fine. I've attached the log for you to take a look at. 

Please let me know if there's anything else I can do or supply you with.

![XrmToolBox FetchXml About](https://user-images.githubusercontent.com/16100407/91958990-f9cd0500-ecff-11ea-8eaa-4ae1fc7050da.png)
[XrmToolBox.FetchXml.Log.txt](https://github.com/rappen/FetchXMLBuilder/files/5161031/XrmToolBox.FetchXml.Log.txt)

**Comment by rappen** [comment] 2020-09-02 10:34
I know, unfortunately... 😕
Duplicate of #345, will be fixed in next release, which I hope is soon out there...

Thanks for reporting!

**Closed by rappen** 2020-09-02 10:34 UTC

**Comment by DiggaTheWolf** [comment] 2020-09-02 10:58
Thanks for the update, and good luck getting this out the door.

**Comment by rappen** [comment] 2020-09-21 21:19
Fix is now released in version 1.2020.9.1 🙂

**Comment by DiggaTheWolf** [comment] 2020-09-22 06:58
All fine now Jonas, very much appreciated.
