### ISSUE TITLE
"Formatted" right apostrophe incorrectly being treated as a regular apostrophe

### ISSUE THREAD

**Issue by ThreeTen22** [rappen/FetchXMLBuilder#569] opened 2021-09-22 22:58 UTC
I got a nice fun issue for you.
It seems that the dataverse does not consider a formatted apostrophe (` ’ `) in text as equal to a regular one (`'` ) 

(ex: if a text holds this value:  `Homeowners’ Association` providing the value  `Homeowners’ Association`  in both fetchxml and power automate's $filter does thee trick.  but providing   `Homeowners&apos; Association`  and `Homeowners'' Association` does not.

(` ’ `) however is incorrectly being replaced with `&apos; `and `''` by fetchxmlbuilder and power automate query builder respectively.

I don't know why microsoft decided to do this...but here we are

**Comment by rappen** [comment] 2021-09-29 12:34
Hmmm....
Tried some time... don't see the problem 🤔
Maybe @MarkMpn can see something?

**Comment by MarkMpn** [comment] 2021-09-29 12:42
I can't reproduce this. I've set up the query:

![image](https://user-images.githubusercontent.com/31017244/135270142-4391fda6-0480-4a8e-a1e9-36d2b6c08f8b.png)

This produces the expected FetchXML:

```xml
<fetch>
  <entity name="account">
    <attribute name="name" />
    <filter>
      <condition attribute="name" operator="eq" value="Homeowners’ Association" />
    </filter>
  </entity>
</fetch>
```

Converting this to Power Automate parameters gives the filter clause:

`(name eq 'Homeowners’ Association')`

Can you give me a step-by-step guide to reproduce the problem?

**Comment by ThreeTen22** [comment] 2021-11-02 23:39
Apologies for the late response.  Guess it was a version specific issue.  I cannot reproduce it anymore after I updated to the latest version.

**Comment by rappen** [comment] 2021-11-03 09:48
Ok so I close it now. Open if it happens again!

**Closed by rappen** 2021-11-03 09:48 UTC
