### ISSUE TITLE
Unable to Query by GUID In latest Version

### ISSUE THREAD

**Issue by ACECEO** [rappen/FetchXMLBuilder#353] opened 2020-08-07 15:21 UTC
The latest version seems to have eliminated the ability to query by record GUID. Now when I attempt to do this, Xrmtoolbox crashes. It does not allow me to choose an operator such as Equal. I needed to restore the previous version to restore this critically important functionality.

**Comment by MarkMpn** [comment] 2020-08-07 17:51
Duplicate of #345, will be fixed in next release.

**Closed by MarkMpn** 2020-08-07 17:51 UTC

**Comment by rappen** [comment] 2020-09-21 21:20
Fix is now released in version 1.2020.9.1 🙂
