### ISSUE TITLE
Query Expression view, on version 1.2020.12.3, is broken. Failed to generate C# QueryExpression code.  

### ISSUE THREAD

**Issue by mtnmuncher** [rappen/FetchXMLBuilder#439] opened 2020-12-17 23:02 UTC
Method not found: 'Boolean Microsoft.Xrm.Sdk.Query.ConditionExpression.get_
![fxb_query_expression_view_broken](https://user-images.githubusercontent.com/6696112/102554086-0fd5ba00-4092-11eb-8aec-184b00fe88ab.png)
CompareColumns()'.

**Comment by rappen** [comment] 2020-12-18 07:54
Duplicate of #438, should be fixed if you use latest XrmToolBox version.
Which version are you using?

(PS - when creating a new issue from within XrmToolBox, the github issue is pre populated with various version info - it helps analyzing the problem 🙂)

**Comment by mtnmuncher** [comment] 2020-12-18 11:11
Got latest. All is well in the world again. Am curious, how do I "create a new issue from within XTB"? Cheers!

**Comment by rappen** [comment] 2020-12-18 11:41
This! 😊
![image](https://user-images.githubusercontent.com/2572253/102610907-47923f80-412e-11eb-959e-b7b522b50478.png)

**Closed by rappen** 2020-12-18 11:41 UTC
