### ISSUE TITLE
Output columns does not match the FetchXML statement

### ISSUE THREAD

**Issue by rgsiiiya** [rappen/FetchXMLBuilder#289] opened 2020-04-21 01:11 UTC
Output columns does not match the FetchXML statement

output does not include all the columns.
This was originally build with Advanced Find, and all the cols show up in Advanced Find,
But when loaded into this tool, it does not show all the cols.

<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false" >
    <entity name="cdr_stagingapplication" >
        <attribute name="cdr_applicationtype" />
        <attribute name="cdr_acquisitionscompleted" />
        <link-entity name="new_projectphase" from="new_projectphaseid" to="cdr_project" link-type="inner" alias="aa" >
            <attribute name="cdr_applicationtype" />
            <attribute name="cdr_acquisitionscompleted" />
        </link-entity>
    </entity>
</fetch>

![fetchbug2](https://user-images.githubusercontent.com/17300494/79814180-dbf79880-833a-11ea-9bd3-2f53bafa3ac2.png)

**Comment by MarkMpn** [comment] 2020-04-21 11:19
Are these columns populated? If they are null for all the returned records, this may be a dupe of #275

**Closed** 2020-05-10 19:00 UTC
