### ISSUE TITLE
Unhandled exception when selecting primary key in filter condition

### ISSUE THREAD

**Issue by gregowens** [rappen/FetchXMLBuilder#377] opened 2020-09-21 10:07 UTC
Repro steps:

- Create new query
- Set entity to `account` (similar scenario fails for all entities)
- right-click `entity` node, add `filter`
- right-click `filter` node, add `condition`
- set `attribute` in `condition` to `account (id)`
- Error message is immediately raised:

> ************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Cinteros.Xrm.FetchXmlBuilder.Controls.conditionControl.RefreshOperators()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

- also note that if I "continue" in response to the error, no `Operator` options are presented 

---
- Deployment: Online
- DB Version: 9.1.0.22845
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 1.2020.7.3

**Comment by rappen** [comment] 2020-09-21 10:14
Thanks for reporting!

Duplicate of #345, fixed in next release :)

**Closed by rappen** 2020-09-21 10:14 UTC

**Comment by rappen** [comment] 2020-09-21 21:18
Fix is now released in version 1.2020.9.1 🙂
