### ISSUE TITLE
Error at filter condition

### ISSUE THREAD

**Issue by catalin-ilie** [rappen/FetchXMLBuilder#350] opened 2020-07-29 09:24 UTC
![image](https://user-images.githubusercontent.com/52157754/88782574-6b141800-d196-11ea-9bb0-0c9b559fc0c8.png)

**Comment by rappen** [comment] 2020-07-29 11:11
Duplicate of #345, will be fixed for next release.

**Closed** 2020-09-20 21:24 UTC

**Comment by rappen** [comment] 2020-09-21 21:21
Fix is now released in version 1.2020.9.1 🙂
