### ISSUE TITLE
Error Displaying Personal View Saved from FetchXMLBuilder

### ISSUE THREAD

**Issue by jjkoran** [rappen/FetchXMLBuilder#776] opened 2022-08-31 17:01 UTC
The following Fetch XML saved as a personal view causes the error shown in the screenshot attached below when executed in Advanced Find Window:

`<fetch>
  <entity name="altai_mbr_participant">
    <attribute name="altai_contactid" />
    <attribute name="altai_mbr_programid" />
    <attribute name="iise_status" />
    <attribute name="altai_paidthrudate" />
    <attribute name="altai_autopay" />
    <attribute name="altai_mbr_participantid" />
    <filter>
      <condition attribute="altai_mbr_programcategory" operator="eq" value="1" />
      <condition attribute="altai_parentparticipationid" operator="null" />
      <condition attribute="iise_renewaldate" operator="eq" value="8/31/2022" />
      <condition attribute="altai_autopay" operator="eq" value="1" />
      <condition attribute="altai_stopbilling" operator="eq" value="0" />
    </filter>
    <link-entity name="contact" from="contactid" to="altai_contactid" alias="contact">
      <attribute name="altai_memberid" />
      <attribute name="fullname" />
      <attribute name="firstname" />
      <attribute name="lastname" />
      <link-entity name="altai_acct_walletentry" from="altai_contactid" to="contactid" link-type="outer" alias="wallet">
        <attribute name="altai_ccexpire" />
        <attribute name="altai_last4" />
        <attribute name="altai_paymenttype" />
        <attribute name="altai_acct_walletentryid" />
        <filter>
          <condition attribute="altai_purpose_autopaydbr" operator="neq" value="467670000" />
        </filter>
      </link-entity>
    </link-entity>
    <link-entity name="altai_mbr_program" from="altai_mbr_programid" to="altai_mbr_programid" alias="program">
      <attribute name="iise_organization_type" />
      <attribute name="iise_member_type" />
    </link-entity>
  </entity>
</fetch>`

![FetchXMLError](https://user-images.githubusercontent.com/12628108/187736845-c7f85598-dc9a-447a-9a7c-a45aea2de8eb.png)

**Comment by rappen** [comment] 2022-09-03 10:24
I just tried with an exact similar query as yours. In FXB it runs well, in Advance Find it crashes, just like in your message above.
Unfortunately, the `fetch` (and then also *FetchXML Builder*) can do 'more' things than the old classy Dynamics 365 views.
Sorry, I can't fix it... 😕

**Comment by jjkoran** [comment] 2022-09-03 10:29
I assumed that.  I was wondering if you knew the part of the query that caused the crash so you could document it.  The outer join?

Sent from my iPhone

On Sep 3, 2022, at 6:24 AM, Jonas Rapp ***@***.***> wrote:

﻿

I just tried with an exact similar query as yours. In FXB it runs well, in Advance Find it crashes, just like in your message above.
Unfortunately, the fetch (and then also FetchXML Builder) can do 'more' things than the old classy Dynamics 365 views.
Sorry, I can't fix it... 😕

**Comment by rappen** [comment] 2022-09-03 13:24
I was digging down a bit more to your query...
The query is all good, and executing the query in Adv.Find is fine.
The problem is "just" showing it...
I have created views with showing "two levels down" columns previously.
I need to look a bit more at when it works, and when it breaks the layout in the Model Driven apps.

See here what makes it break, the highlight attributes. You can even include them in the query, but not showing them.

![image](https://user-images.githubusercontent.com/2572253/188272353-54a7b681-49da-4332-98ff-ebf267d71809.png)

**Comment by rappen** [comment] 2022-09-03 13:41
Nope! The issue is in the Adv.Find - it DOES WORK is the normal view!
I just found that... :)

Although, names of the columns that are 2+ levels down are getting fishy or none names... MS has some work to do there.

**Comment by jjkoran** [comment] 2022-09-12 12:16
Thanks for the response. I love this new feature and just trying to know the limits.   There are a lot of advanced queries we would like our users to be able to run that our IT dept currently has to run.    I will not hold my breath waiting for MS to fix the Advanced Find!

J. J. Koran
Director of Finance & Information Technology | Institute of Industrial and Systems Engineers
(770) 349-1111 | ***@***.******@***.***>
www.iise.org<http://www.iise.org/>

Topgolf, meet n greets, trending speakers and hot topics are on tap in Atlanta Sept. 19-21. Sign up for #Lean6Data2022<http://www.iise.org/Lean6Data> now & save! For year-round on-site and on-demand career-enhancing courses, go to iise.org/TrainingCenter<http://iise.org/TrainingCenter>.

**Comment by rappen** [comment] 2022-09-12 14:02
True true, MS will not fix/improve the old OLD Advance Find... It will go die, when the new things are ready.
If they skip get new feature in param with the old one - well I guess I should start to sell FXB instead of being free... 😏

**Comment by rappen** [comment] 2022-09-12 14:03
Closing this - can't be fixed "on my side".
Ok?

**Closed by rappen** 2022-09-12 14:03 UTC
