### ISSUE TITLE
Workaround Inner Joins not supported in oData Query

### ISSUE THREAD

**Issue by DREWLFE** [rappen/FetchXMLBuilder#378] opened 2020-09-25 16:29 UTC
I tried to do an inner join with a linked entity and filter on the linked entity which works great but fetchXMLBuilder just tells me:
OData queries do not support inner joins on 1:N relationships.

I worked around this using the any operator such as: /api/data/v9.1/accounts?$select=name%20&$filter=opportunity_customer_accounts/any(o:o/closeprobability%20eq%2090)

I repurposed that for my scenario with Contacts and a custom child entity.  I wanted to find all contacts that had a child entity with some property.  I couldn't see how to build an any query using FetchXML Builder.  Did I just not look hard enough or does it not support them?

Unless I've misunderstood what's happening this any query can be used in place of an inner join query and is the way to do them in OData.  Is that right and is it something that you can teach Builder how to do?

**Comment by MarkMpn** [comment] 2020-10-02 14:24
I'll be looking at this shortly, closing as a dupe of #272

**Closed by MarkMpn** 2020-10-02 14:24 UTC
