### ISSUE TITLE
IN query- exception

### ISSUE THREAD

**Issue by vinodhbojan** [rappen/FetchXMLBuilder#277] opened 2020-02-04 18:17 UTC
When I execute the query using the IN operator with comma separated values, I get the error that the value passed in is empty. Please see screen shot attached.

This used to work fine until a few weeks ago. 

![FXB IN operator](https://user-images.githubusercontent.com/60667384/73773426-c3b6ab00-4747-11ea-8767-81cd7016b847.png)

Thanks!-
VB

**Comment by MarkMpn** [comment] 2020-02-05 14:04
I have a feeling this might be caused by the changes I made recently to update the FetchXML as you change the node properties. I'll take a look at this now.

**Comment by MarkMpn** [comment] 2020-02-05 14:05
In the meantime you can add the individual values separately by right-clicking on the `condition` node in the query builder and adding `value` nodes to it.

**Comment by vinodhbojan** [comment] 2020-02-05 15:27
At this point, I have a long list of values and adding them one by one may not work out for me. I will play around some more with this.

Thanks for looking into this. Appreciate it!

    On Wednesday, February 5, 2020, 08:05:19 AM CST, MarkMpn <notifications@github.com> wrote:  
 
 
In the meantime you can add the individual values separately by right-clicking on the condition node in the query builder and adding value nodes to it.

**Comment by MarkMpn** [comment] 2020-02-05 15:48
In that case your best option for the moment might be to do a bit of find & replace in your favourite text editor to change your values from:

`1,2`

to

`<value>1</value><value>2</value>`

You can then copy & paste that into the raw FetchXML view (`View` > `FetchXML`)

Your existing condition will look like:

```xml
<condition attribute="accountnumber" operator="in" value="1,2" />
```

You'll need to remove the `value=""` attribute and trailing `/`, paste in your values after the closing `>` and then add a `</condition>` at the end, so you'll end up with:

```xml
<condition attribute="accountnumber" operator="in">
  <value>1</value>
  <value>2</value>
</condition>
```

**Comment by vinodhbojan** [comment] 2020-02-05 17:08
Great! Exactly what I had in mind but was not sure if I could edit the raw fetch xml view.
Thanks for that tip- will try it.
Sent from Yahoo Mail for iPhone


On Wednesday, February 5, 2020, 9:48 AM, MarkMpn <notifications@github.com> wrote:


In that case your best option for the moment might be to do a bit of find & replace in your favourite text editor to change your values from:

1,2

to

<value>1</value><value>2</value>

You can then copy & paste that into the raw FetchXML view (View > FetchXML)

Your existing condition will look like:
<condition attribute="accountnumber" operator="in" value="1,2" />
You'll need to remove the value="" attribute and trailing /, paste in your values after the closing > and then add a </condition> at the end, so you'll end up with:
<condition attribute="accountnumber" operator="in">
  <value>1</value>
  <value>2</value>
</condition>

**Closed** 2020-02-05 18:43 UTC
